src/App.js
src/components/Appbar.js
src/components/Sidebar.js

small formatting changes and removing console log errors

Mikayla sidebar

---

package.json
src/App.js
src/app/actions/index.js
src/app/reducers/index.js
src/app/reducers/selectedContentPage.js
src/app/reducers/toggleSidebar.js
src/components/Appbar.js
src/components/Feed.js
src/components/Followers.js
src/components/Following.js
src/components/Login.js
src/components/NowPlaying.js
src/components/Profile.js
src/components/Settings.js
src/components/Sidebar.js
src/index.js
yarn.lock

- implemented navigation with react router for sidebar/app bar
- created some temp place holder components (Profile, Settings, Feed, etc.)
- for now, all URLS are relative to logged in user but sidebar URLS will eventually reflect "current" user
- made sidebar buttons clickable even when sidebar is collapsed
- commented out code that was used for temporary navigation for our last demo

Mikayla router

---

package.json
src/App.js
src/app/actions/index.js
src/app/reducers/index.js
src/app/reducers/settings.js
src/components/Appbar.js
src/components/Settings.js
src/components/Sidebar.js
src/data/ContentTypeEnum.js
src/index.js
yarn.lock

- implemented light mode/darkmode theme change when button is toggled in settings page
- changed sidebar "POST" to "ALBUMS" as discussed in our last meeting

Mikayla dark mode

---

package.json
src/app/actions/index.js
src/app/reducers/index.js
src/app/reducers/settings.js
src/components/Appbar.js
src/components/Settings.js
src/components/Sidebar.js
src/index.js
yarn.lock

Created a simple Settings page component with some default settings and connected it to the Redux Store

Mikayla settingspage

---

server/models/user-model.js

changed schema.object id type to string

---

client/src/App.js
client/src/app/actions/spotifyApiActions.js
client/src/components/SongList.js
client/src/components/profile/ProfileCard.js
server/models/user-model.js

Login process creates new user in db if it does not already exist;
else get response: 400 and user remains unchanged.
NOTE: app login and spotify features run independently from mongodb info.
Added song sample playback in profile card.

austin-profile-card

---

client/src/app/actions/feedActions.js
client/src/app/actions/postActions.js
client/src/app/reducers/feed.js
client/src/components/feed/Feed.js
server/controllers/user-controller.js

refactored db query so Feed is a single component connected to the Feed Store

Mikayla feed tidy

---

client/src/app/actions/feedActions.js
client/src/app/actions/imageUploadActions.js
client/src/app/actions/postActions.js
client/src/app/actions/settingsActions.js
client/src/components/ImageUpload.js
client/src/components/Profile.js
client/src/components/feed/Feed.js
client/src/components/feed/Post.js
client/src/components/profile/ProfileCard.js
server/controllers/user-controller.js

implemented ability to render profile pic on posts and user cards

---

client/src/app/actions/spotifyApiActions.js
client/src/components/profile/ProfileCard.js

reafactored profile card to use db data from user_ID props passed in from parent

austin-refactor-profilecard-try2

---

client/src/components/feed/Post.js

Added UI for comments on Posts

minor styling changes and added comment accordian

---

client/src/App.css
client/src/components/Tinderify.js

Style changes to tinderify page to make it look nicer with dark mode

Sarchen tinderify style changes

---

client/src/app/actions/index.js
client/src/app/actions/postActions.js
client/src/app/reducers/delPostDialog.js
client/src/app/reducers/index.js
client/src/components/DeletePostDialog.js
client/src/components/Profile.js
client/src/components/feed/Post.js
server/controllers/user-controller.js
server/routes/user-routes.js

added the ability to delete posts from your profile/feed with dialog confirmation

Mikayla delete post

---

client/src/components/Albums.js
client/src/components/Favourites.js
client/src/components/Playlists.js
client/src/components/Sidebar.js
client/src/components/SongList.js

Songs in Albums/Playlists and Favourites can now be added to MySpot playlist.

Add to myspot playlist

---

client/src/components/Albums.js
client/src/components/Playlists.js
client/src/components/SongList.js

navigation from albums to songlist should no longer cause app to crash

fixed links in albums; updated prop names

---

client/src/components/Appbar.js
client/src/components/SongList.js
client/src/components/feed/Post.js
client/src/components/feed/PostComment.js

- fixed postcomment styling
- fixed songllist go back button
- increased myspot font weight

Mikayla styling 2

---

client/src/components/Settings.js
client/src/components/Sidebar.js
client/src/components/SongList.js
client/src/components/profile/Profile.js

-moved settings and profile pic dispatchers to Sidebar so they're only called once at login
-changed back dispatchers from succcess to fetch

austin-fix-settings-profilepic-redux

---

client/src/components/profile/Profile.js

removed profile pic and settings dispatches in profile

---

client/src/components/tinderify/MusicBrowser.js

user sees message to like discover weekly playlist if they dont already.
if friend doesnt have discover weekly liked/public, myspot playlist used as backup.

tinderify bug fix

---

client/src/components/follow/FollowButton.js
client/src/components/follow/FollowTable.js
client/src/components/profile/ProfileCard.js

- fix follow button when going between profiles that don't each have follow or each have following

Quinn fix follow button persist and fixed country flag for US

---

client/src/app/actions/imageUploadActions.js
client/src/app/actions/postActions.js
client/src/app/actions/settingsActions.js
client/src/components/follow/FollowButton.js

as title - may need to fix ones in server www

Quinn remove throws from dev

---

client/src/components/Sidebar.js
client/src/components/feed/MakePost.js
client/src/components/profile/ProfileTable.js
client/src/components/tinderify/FriendsDiscoverWeekly.js

just added the fixes we made on clean up branch last night

Quinn fixes added to cleanup

---

client/src/components/Albums.js
client/src/components/Playlists.js

links to spotify playlists and albums

added link to spotify for albums playlists

---

client/src/components/Favourites.js
client/src/components/SongList.js
client/src/components/feed/MakePost.js
client/src/components/profile/ProfileTable.js
client/src/components/tinderify/MusicBrowser.js

- Check commit messages for each change
- first commit is the same minor fixes we (sarchen) did on the quinn-code-cleanup before last deploy

Quinn quick fixes
